-- MASTER DATABASE ROLLBACK/CLEANUP SCRIPT
SET DEFINE OFF
SET SQLBLANKLINES ON

PROMPT [1/7] Dropping DBMS_SCHEDULER Jobs...
BEGIN
  BEGIN DBMS_SCHEDULER.DROP_JOB('job_equipment_alerts'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DBMS_SCHEDULER.DROP_JOB('job_monthly_review'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DBMS_SCHEDULER.DROP_JOB('job_error_log_purge'); EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

PROMPT [2/7] Dropping Triggers...
BEGIN
  FOR r IN (SELECT trigger_name FROM user_triggers) LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER ' || r.trigger_name;
  END LOOP;
END;
/

PROMPT [3/7] Dropping PL/SQL Packages...
BEGIN
  FOR r IN (SELECT object_name FROM user_objects WHERE object_type = 'PACKAGE') LOOP
    EXECUTE IMMEDIATE 'DROP PACKAGE ' || r.object_name;
  END LOOP;
END;
/

PROMPT [4/7] Dropping Views...
BEGIN
  FOR r IN (SELECT view_name FROM user_views) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ' || r.view_name;
  END LOOP;
END;
/

PROMPT [5/7] Dropping Tables with CASCADE CONSTRAINTS...
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE BUYER_FACTORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE SALARY_RECORD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE GRIEVANCE_AUDIT_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE GRIEVANCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE SAFETY_EQUIPMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE CERTIFICATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE "AUDIT" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_ CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE WORKER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE BUYER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE FACTORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE ERROR_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE SAFETY_ALERT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

PROMPT [6/7] Dropping Sequences...
BEGIN
  FOR r IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.sequence_name;
  END LOOP;
END;
/

PROMPT [7/7] Dropping Database Roles...
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP ROLE compliance_officer_role'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP ROLE inspector_role'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP ROLE buyer_role'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP ROLE worker_role'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

PROMPT Schema rollback successfully finished. All GarmentGuard objects dropped.
EXIT;
